### ISSUE TITLE
Ethernet on VC707 or VCU118

### ISSUE THREAD

**Issue by jctullos** [sifive/fpga-shells#124]
@erikdanie 

Hey Erik or anyone else that could answer,

Was there a reason the ethernet was decided to be used through the PCIe FMC module rather than through the onboard ethernet on the VC707 or VCU118? 

I don't have the FMC module, so I was going to work on getting the onboard ethernet working but if there was an issue that made using an expansion ethernet card with the PCIe FMC easier then I'll disregard that avenue and see if I can get approval to get it. 

Thank you all,
Justin

**Comment by erikdanie** [comment]
Hi Justin,

Ethernet over PCIe was a natural choice, given that PCIe had been onboarded, and it was as simple as plugging in an ethernet card. The ethernet adapter requires onboarding of a controller, which adds complication. There is a license-free Xilinx Ethernet Axi-Lite IP that can be used, and we attempted this for the Arty100T some time ago, but ran into issues on the tilelink side, and had to halt work on it. This is on the `arty-ethernet` branch if you care to take a look. I imagine we will try to get it working at some point, but currently can't provide any support for that in the near future.

**Comment by jctullos** [comment]
Hey Erik,

Thank you for the explanation and makes sense.
